puts "Seeding products..."
Product.create!([ 
    { id: 1, name: "Fig's Finest", price: 18.00, isSingle_origin: true, isFeatured: true, isCoffee: true, description: "Have you met Fig? They're one of our roasters. They also have anxiety. They stay up late into the night, looking for that perfect roast, blend, and grind. Why, you ask? Because that's what it takes! Because that's who they are. Because who are they, if they can't find that perfect coffee? What is their worth without that perfect coffee? Can anyone love them if they can't make that perfect cup of coffee? So they work very hard to make that perfect cup of coffee. Featuring: Fig's Finest, the finest coffee anxiety can make. It turns out, that's pretty fine coffee." }, 
    { id: 2, name: "Sunny Days Ahead", price: 17.00, isSingle_origin: true, isFeatured: false, isCoffee: true, description: "Depression" }, 
    { id: 3, name: "3AM", price: 30.00, isSingle_origin: false, isFeatured: true, isCoffee: true, description: "Bipolar" },
    { id: 4, name: "Blonde Distraction", price: 40.00, isSingle_origin: false, isFeatured: false, isCoffee: true, description: "Sex Addiction/obsessive behaviors" },
    { id: 5, name: "Whispers Over Yonder", price: 50.00, isSingle_origin: false, isFeatured: false, isCoffee: true, description: "Schizophrenia" },
    { id: 6, name: "Origami Dripper", price: 40.00, isSingle_origin: null, isFeatured: true, isCoffee: false, description: "Picture it: a staff breakroom with quaint brick walls, big, sunny windows, plush, cozy couches, and string lights. At the center is an espresso machine, sleek and expensive. No one even looks at it. Instead, to the left side of the office is a counter with a pour over set up. They have nothing against french press coffee, they say, sending furitive glances to the right side of the office. But they love the ritual of pour overs: the quiet moments as the coffee blooms, the conversation as it drips, the human moments. This is the same dripper we use: utilizing a design that can accommodate both flat-bottom and conical filters, the Origami also boasts a large aperture to ensure unclogged, even flow rate. It is also made of minoware clay, a ceramic-making technique with a rich Japanese tradition and excellent heat-retention qualities. This dripper is good for making about 1-4 cups per brew. And no one has to think about how much money I spent on that espresso machine." },
    { id: 7, name: "Bodum Chamboard French Press", price: 40.00, isSingle_origin: null, isFeatured: false, isCoffee: false, description: "Picture it: a staff breakroom with quaint brick walls, big, sunny windows, plush, cozy couches, and string lights. At the center is an espresso machine, sleek and expensive. No one even looks at it. Instead, to the right side of the office is a counter with a french press set up. They have nothing against pour over coffee, they say, sending surreptitious glances to the left side of the office. But they love the efficiency of french presses: the ease of setting the coffee and leaving it, the conversation as it steeps, the human moments. This is the same french press we use: the carafe is made of non-stain, heat-resistant borosilicate glass, the top is made of durable, shiny stainless steel, and the beautifully designed frame is made of brass. This french press is good for making about 1-4 cups per brew. And no one has to think about how much money I spent on that espresso machine." },
    { id: 8, name: "The Bripe", price: 99.00, isSingle_origin: null, isFeatured: false, isCoffee: false, description: "Picture it: a staff breakroom with quaint brick walls, big, sunny windows, plush, cozy couches, and string lights. At the center is an espresso machine, sleek and expensive. No one even looks at it. Instead, to the left side of the office is a counter with a pour over set up. To the right side, a counter with a french press set up. Both sides eye each other warily as they make their coffee, the very expensive espresso machine completely ignored. And on the opposite end of the office is a small faction of employees watching everything play out with a curious device: a small brass pipe that makes great coffee in the great outdoors (or anywhere else). No electricity, gas canister, kettle, or stove is needed to light this pipe. The Bripe only requires ground coffee and water, and includes a portable butane-powered quad jet torch that I definitely did not authorize in the employee break room. Each staff member with a Bripe enjoys rich conversation as they light the small device and brew rich shots of coffee. And no one has to think about how much money I spent on that espresso machine." },
    { id: 9, name: "Handleless Frothing Pitcher with Narrow Spout", price: 90.00, isSingle_origin: null, isFeatured: false, isCoffee: false, description: "This is a description of product 9" },
    { id: 10, name: "Sticker Pack", price: 100.00, isSingle_origin: null, isFeatured: false, isCoffee: false, description: "This is a description of product 10"}
    { id: 11, name: "Coffee Mug", price: 110.00, isSingle_origin: null, isFeatured: false, isCoffee: false, description: "This is a description of product 11"},
    { id: 12, name: "Coffee Tote", price: 120.00, isSingle_origin: null, isFeatured: false, isCoffee: false, description: "This is a description of product 12"}])

puts "Seeding complete!"